"""
Agent 4 — Delivery
Two outputs:
  1. Saves a markdown summary to the Obsidian vault:
     C:\\Users\\aryam\\Desktop\\Jarvis Brain\\04 - AI News\\YYYY-MM-DD.md
  2. Emails the HTML report via Gmail SMTP (same setup as Candle Intel)
"""

import os
import smtplib
from datetime import date, datetime
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

VAULT_AI_NEWS = Path(r"C:\Users\aryam\Desktop\Jarvis Brain\04 - AI News")


# ── Load ──────────────────────────────────────────────────────────────────────

def load_latest_html(reports_dir: str = "reports") -> tuple[str, str]:
    files = sorted(Path(reports_dir).glob("briefing_*.html"), reverse=True)
    if not files:
        raise FileNotFoundError(
            "No HTML report found in reports/. Run agent3_report.py first."
        )
    path = files[0]
    with open(path, encoding="utf-8") as f:
        return f.read(), str(path)


def load_latest_scored(data_dir: str = "data") -> list[dict]:
    import json
    files = sorted(Path(data_dir).glob("scored_*.json"), reverse=True)
    if not files:
        return []
    with open(files[0], encoding="utf-8") as f:
        return json.load(f)


# ── Output 1: Obsidian markdown ───────────────────────────────────────────────

CATEGORY_EMOJI = {
    "NEW_TOOL":     "⚡",
    "TUTORIAL":     "📖",
    "BUSINESS_OPP": "💰",
    "JUST_NEWS":    "📰",
}


def build_markdown(items: list[dict], date_str: str) -> str:
    date_fmt = datetime.strptime(date_str, "%Y-%m-%d").strftime("%B %d, %Y")
    total = len(items)
    action_count = sum(1 for i in items if i.get("action_required"))
    avg_score = round(sum(i.get("ai_score", 0) for i in items) / total, 1) if total else 0

    lines = [
        f"# Jarvis AI Briefing — {date_fmt}",
        "",
        f"> **{total} items** · Avg score **{avg_score}/10** · **{action_count}** require action",
        "",
        "---",
        "",
    ]

    # Group by category, priority order
    cat_order = ["NEW_TOOL", "BUSINESS_OPP", "TUTORIAL", "JUST_NEWS"]
    cat_labels = {
        "NEW_TOOL":     "New Tools",
        "BUSINESS_OPP": "Business Opportunities",
        "TUTORIAL":     "Tutorials",
        "JUST_NEWS":    "News",
    }

    for cat in cat_order:
        cat_items = [i for i in items if i.get("ai_category") == cat]
        if not cat_items:
            continue

        emoji = CATEGORY_EMOJI.get(cat, "📰")
        lines.append(f"## {emoji} {cat_labels[cat]}")
        lines.append("")

        for item in cat_items:
            score  = item.get("ai_score", 0)
            title  = item.get("title", "Untitled")
            url    = item.get("url", "#")
            reason = item.get("ai_reason", "")
            source = item.get("source", "")
            action = " 🔥 ACTION" if item.get("action_required") else ""

            lines.append(f"### [{title}]({url})")
            lines.append(f"**Score:** {score}/10 · **Source:** {source}{action}")
            lines.append(f"> {reason}")
            lines.append("")

    lines += [
        "---",
        "",
        f"*Generated by Jarvis AI News Agent · {date_fmt} · Groq / LLaMA 3.3 70B*",
    ]

    return "\n".join(lines)


def save_to_vault(items: list[dict]) -> str:
    date_str = date.today().isoformat()
    VAULT_AI_NEWS.mkdir(parents=True, exist_ok=True)

    md_content = build_markdown(items, date_str)
    out_path   = VAULT_AI_NEWS / f"{date_str}.md"

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(md_content)

    print(f"  Saved to vault: {out_path}")
    return str(out_path)


# ── Output 2: Email ───────────────────────────────────────────────────────────

def build_plain_text(date_fmt: str, item_count: int) -> str:
    return f"""Jarvis AI Briefing — {date_fmt}

Your daily AI intelligence digest is ready.
{item_count} items scored and curated from HackerNews, ProductHunt, and Reddit r/artificial.

Open the HTML attachment or view this email in a modern client for the full report.

---
Generated by Jarvis AI News Agent
Powered by Groq / LLaMA 3.3 70B
"""


def send_email(html_content: str, html_path: str, item_count: int) -> None:
    sender       = os.environ.get("EMAIL_ADDRESS")
    app_password = os.environ.get("EMAIL_PASSWORD")
    recipient    = os.environ.get("TO_EMAIL")

    missing = [k for k, v in {
        "EMAIL_ADDRESS":  sender,
        "EMAIL_PASSWORD": app_password,
        "TO_EMAIL":       recipient,
    }.items() if not v]

    if missing:
        raise EnvironmentError(
            f"Missing in .env: {', '.join(missing)}\n"
            "Set EMAIL_ADDRESS, EMAIL_PASSWORD (Gmail App Password), and TO_EMAIL."
        )

    date_fmt = date.today().strftime("%B %d, %Y")
    subject  = f"Jarvis AI Briefing — {date_fmt}"

    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"]    = f"Jarvis AI Agent <{sender}>"
    msg["To"]      = recipient

    alt = MIMEMultipart("alternative")
    alt.attach(MIMEText(build_plain_text(date_fmt, item_count), "plain"))
    alt.attach(MIMEText(html_content, "html"))
    msg.attach(alt)

    # Attach HTML file
    filename = Path(html_path).name
    with open(html_path, "rb") as f:
        attachment = MIMEBase("application", "octet-stream")
        attachment.set_payload(f.read())
    encoders.encode_base64(attachment)
    attachment.add_header("Content-Disposition", "attachment", filename=filename)
    msg.attach(attachment)

    print(f"  Connecting to smtp.gmail.com:587...")
    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.ehlo()
        server.starttls()
        server.login(sender, app_password)
        server.sendmail(sender, recipient, msg.as_string())

    print(f"  Sent to {recipient}")


# ── Entry point ───────────────────────────────────────────────────────────────

def run() -> None:
    print(f"\n{'='*60}")
    print("  AGENT 4 -- DELIVERY")
    print(f"{'='*60}\n")

    # Load data
    items                    = load_latest_scored()
    html_content, html_path  = load_latest_html()

    print(f"  {len(items)} items to deliver")
    print(f"  HTML report: {html_path}\n")

    # Output 1: Obsidian vault
    print("  [1/2] Saving to Obsidian vault...")
    save_to_vault(items)

    # Output 2: Email
    print("\n  [2/2] Sending email...")
    try:
        send_email(html_content, html_path, len(items))
        print("  [OK] Email delivered successfully.\n")
    except EnvironmentError as e:
        print(f"  [SKIP] Email skipped: {e}\n")
    except Exception as e:
        print(f"  [ERROR] Email failed: {e}\n")
        raise


if __name__ == "__main__":
    run()
